### ISSUE TITLE
Question on engine usage? 

### ISSUE THREAD

**Issue by MetalMaxMX** [aknetk/HatchGameEngine#10]
So I saw this engine from the OpenMania + Hatch Game engine demostration video on youtube (https://www.youtube.com/watch?v=-4J1RWOKbe8) and I found it pretty cool, it seems like it'd be able to handle other types of 2D pixel platformers very well so I wanted to ask: 

1) What can the user do with this engine? More specifically, is there any type of particular license with it? (I know the author has stated that he left this repo as is due to portfolio reasons, but that doesn't clear up about what can the user be allowed to do with this) 

2) Will there be more videos or demonstrations on the engine? 

That's all from me, cheers!

**Comment by aknetk** [comment]
I'll add a written out MIT license to the repo, but yeah you can do whatever, go wild lol
